### PR TITLE
Update getNameFromClassBody to remove path

### PR DESCRIPTION
**Pull request by mgarf**
* Added code that split out the document path and pulled only the filename from the path.

This should prevent the issue the path issue. I wasn't able to test as I haven't the time to set up an environment to properly get this tested. I'll leave the pull request open for someone to test before merging goes and if I find some time ill test it myself and comment here. #6

### CODE REVIEW

**Comment by mgarf** [comment]
@celador Tested on Windows 10 and it works.

**Comment by mgarf** [comment]
@celador Tested on Windows 10

**Comment by DougJod** [comment]
Has this fix been packaged and released? I'm getting this error after installing the extension through the IDE. I haven't tried installing from source.

**Comment by celador** [comment]
I'll take a look at it tonight or tomorrow. Thanks for the heads up. Sorry
about the brokenness.

**Pull request merged**
